inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails

AllCops:
  TargetRubyVersion: 2.5.1
  Exclude:
    - 'config.ru'
    - 'bin/**'
    - 'lib/**'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'spec/**'
    - 'spec/**/*'
    - 'spec/**/**/*'
    - 'lib/**/*'
    - 'test/**'
    - !ruby/regexp /old_and_unused\.rb$/

AsciiComments:
  Enabled: false

Documentation:
  Enabled: false

ClassAndModuleChildren:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/AbcSize:
  Max: 24

Metrics/MethodLength:
  Max: 12

Metrics/ClassLength:
  Max: 120